Update to new jsx runtime and bump major version
grafana/tsconfig-grafana pull request #7
Opened 2024-06-17 10:09 UTC by ashharrison90

prereq for https://github.com/grafana/grafana/pull/88802/

2024-06-19 08:20 UTC, jackw commented
>won't merge and release until we're all ready in core as well 👍

This package is also used by plugins. If a plugin dev updates this will they need to update their eslint config and webpack config too?

2024-06-19 08:58 UTC, ashharrison90 commented
> > won't merge and release until we're all ready in core as well 👍
> 
> This package is also used by plugins. If a plugin dev updates this will they need to update their eslint config and webpack config too?

yes. do plugins typically manage their own dependencies, or do they rely on `create-plugin` to update them? or some mixture of both? 🤔 

either way, we should probably add a CHANGELOG to this repo to explain the changes. it will be something like:
- update `eslint-config-grafana` as well
- update the build to use new jsx runtime (this step will vary depending on the existing build, e.g. babel, esbuild, etc.)
- run the [react codemod](https://legacy.reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html#removing-unused-react-imports) on the plugin code

2024-06-19 14:11 UTC, tolzhabayev requested changes
We should have a concrete plan first on how and especially when we want to tackle the upgrade, so let's have it in place before we make plugin developers do something we don't really know what exactly it is.

2025-10-20 14:45 UTC, jackw commented
closing this as package is moving to plugin-tools. #13

2025-10-20 14:45 UTC, closed without merging